<script lang="ts">
  import { onMount } from 'svelte';
  import { openUrl } from '@tauri-apps/plugin-opener';
  const base = window.location.port === '5173' ? 'http://127.0.0.1:6770' : window.location.origin;
  type C = { scopeId:number; scopeName:string; subnet:string; prefix:number; ip:string; mac?:string };
  type M = { identity:string; mac?:string; scopeName:string; currentIp:string; configurationStatus:string; onlineStatus:string; redfishStatus:string; authenticationStatus:string; lastCheckedAt?:number };
  let lessorUrl='http://127.0.0.1:8080', scopeId=1, username='admin', currentPassword='', newPassword='', targetPrefix=24, targetGateway='';
  let candidates:C[]=[], managed:M[]=[], targets:Record<string,string>={}, picked:Record<string,boolean>={};
  let loading=false, executing=false, message='正在从 lessor 读取已确认 BMC。', error='', progress='';
  onMount(async()=>{ await defaults(); await Promise.all([load(), inventory()]); });
  async function json(r:Response){ try{return await r.json()}catch{return {}} }
  async function defaults(){ try{const r=await fetch(`${base}/api/v1/settings/defaults`);if(!r.ok)return;const {defaults:d}=await r.json();lessorUrl=d.lessorUrl;scopeId=d.scopeId;username=d.username;targetPrefix=d.targetPrefix;targetGateway=d.targetGateway}catch{} }
  async function load(){ loading=true;error='';try{const q=new URLSearchParams({lessorUrl,scopeId:String(scopeId)});const r=await fetch(`${base}/api/v1/candidates?${q}`);const x=await json(r);if(!r.ok)throw Error(x.error??'无法读取 lessor BMC 列表');candidates=x;targets=Object.fromEntries(x.map((v:C)=>[v.ip,targets[v.ip]??'']));picked=Object.fromEntries(x.map((v:C)=>[v.ip,picked[v.ip]??false]));message=x.length?`已自动读取 ${x.length} 台 lessor 已确认 BMC。`:'当前作用域没有已确认 BMC。'}catch(e){error=e instanceof Error?e.message:'读取失败'}finally{loading=false} }
  async function inventory(){ const r=await fetch(`${base}/api/v1/managed-bmcs`);if(r.ok)managed=await r.json(); }
  async function wait(job:any){while(['queued','running'].includes(job.state)){await new Promise(r=>setTimeout(r,1500));const x=await fetch(`${base}/api/v1/jobs/${job.id}`);job=await json(x)}return job}
  async function execute(){const rows=candidates.filter(x=>picked[x.ip]);if(!rows.length||!username||!currentPassword||!targetGateway||rows.some(x=>!targets[x.ip])){error='请勾选 BMC，并填写共用凭据、网关及每台目标 IPv4。';return}await fetch(`${base}/api/v1/settings/defaults`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({lessorUrl,scopeId,username,targetPrefix,targetGateway})});executing=true;error='';const failed:string[]=[];for(const [i,c] of rows.entries()){progress=`${i+1}/${rows.length}：${c.ip} → ${targets[c.ip]}`;try{const cert=await fetch(`${base}/api/v1/certificates/probe`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessorUrl,scopeId,candidateIp:c.ip})});const cf:any=await json(cert);if(!cert.ok)throw Error(cf.error??'无法读取 HTTPS 证书');const plan=await fetch(`${base}/api/v1/provision/plan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessorUrl,scopeId,candidateIp:c.ip,credentials:{username,currentPassword,newPassword},targetNetwork:{address:targets[c.ip],prefix:targetPrefix,gateway:targetGateway},certificateFingerprint:cf.fingerprint.sha256,passwordChange:false})});const p:any=await json(plan);if(!plan.ok)throw Error(p.details?.reason??p.error??'无法生成内部配置');const apply=await fetch(`${base}/api/v1/provision/plans/${p.planId}/apply`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credentials:{username,currentPassword,newPassword}})});const a:any=await json(apply);if(!apply.ok)throw Error(a.error??'无法提交');const done=await wait(a);if(done.state!=='completed')throw Error(done.error??'配置失败')}catch(e){failed.push(`${c.ip}：${e instanceof Error?e.message:'失败'}`)}}await inventory();executing=false;progress='';message=`批量任务完成：成功 ${rows.length-failed.length} 台，失败 ${failed.length} 台。`;if(failed.length)error=failed.join('；')}
  function set(ip:string,v:string){targets={...targets,[ip]:v}} function choose(ip:string,v:boolean){picked={...picked,[ip]:v}}
  async function open(ip:string){try{if('__TAURI_INTERNALS__' in window)await openUrl(`https://${ip}`);else window.open(`https://${ip}`,'_blank')}catch{error='无法使用默认浏览器打开 BMC 地址'}}
  const label=(v:string)=>({online:'在线',offline:'离线',reachable:'可用',unreachable:'不可达',success:'成功',failed:'失败',unknown:'未检查',completed:'已完成'} as Record<string,string>)[v]??v;
</script>
<main><header><div><p class="eyebrow">BMC provisioning</p><h1>bmc-provisioner</h1></div><span class="local">仅本机 localhost</span></header><p class="notice">启动后自动读取 lessor 已确认 BMC。自签名证书由后台读取并固定校验，不需要手工确认。</p>
<section><div class="section-title"><div><p class="step">01</p><h2>待配置 BMC</h2></div><button onclick={load} disabled={loading||executing}>{loading?'读取中…':'刷新 lessor'}</button></div><div class="fields"><label>lessor 地址<input bind:value={lessorUrl}/></label><label>作用域 ID<input bind:value={scopeId} type="number"/></label><label>用户名<input bind:value={username}/></label><label>当前密码<input bind:value={currentPassword} type="password"/></label><label>新密码（首次强制改密时使用）<input bind:value={newPassword} type="password"/></label><label>前缀<input bind:value={targetPrefix} type="number"/></label><label>网关<input bind:value={targetGateway} placeholder="172.16.40.254"/></label></div><div class="candidate-list"><div class="candidate header-row"><span>选择 / BMC</span><span>MAC / 作用域</span><span>目标静态 IPv4</span></div>{#each candidates as c}<div class="candidate"><label class="pick"><input type="checkbox" checked={picked[c.ip]} onchange={e=>choose(c.ip,e.currentTarget.checked)}/><strong>{c.ip}</strong></label><span><code>{c.mac??'MAC 未返回'}</code><small>{c.scopeName} / {c.subnet}/{c.prefix}</small></span><input value={targets[c.ip]??''} oninput={e=>set(c.ip,e.currentTarget.value)} placeholder="例如 172.16.40.200"/></div>{/each}</div><button class="danger" onclick={execute} disabled={executing||!candidates.length}>{executing?progress:'执行已勾选 BMC 的 IP 变更配置'}</button></section>
<section><div class="section-title"><div><p class="step">02</p><h2>BMC 清单与访问状态</h2></div><button onclick={inventory}>刷新清单</button></div>{#if managed.length}<div class="inventory-table"><div class="inventory-row table-heading"><span>BMC / MAC</span><span>访问地址</span><span>配置</span><span>在线 / Redfish / 认证</span><span>最后检查</span></div>{#each managed as b}<div class="inventory-row"><span><strong>{b.currentIp}</strong><small>{b.mac??b.identity} · {b.scopeName}</small></span><a href={`https://${b.currentIp}`} onclick={e=>{e.preventDefault();void open(b.currentIp)}}>https://{b.currentIp}</a><span>{label(b.configurationStatus)}</span><span>{label(b.onlineStatus)} / {label(b.redfishStatus)} / {label(b.authenticationStatus)}</span><span>{b.lastCheckedAt?new Date(b.lastCheckedAt*1000).toLocaleString():'未检查'}</span></div>{/each}</div>{:else}<p class="muted">完成配置的 BMC 会自动出现在这里。</p>{/if}</section><footer aria-live="polite">{#if error}<p class="error">{error}</p>{/if}<p>{message}</p></footer></main>
